-- INSERT --
INSERT INTO storegroups
VALUES
(1, "REGULAR"),
(2, "SUPPORTER"),
(3, "CONTRIBUTOR"),
(4, "DONATOR");

INSERT INTO storesounds (ItemId, SoundName, SoundFile, Price)
VALUES
("snd_bruh",    "Bruh",             "snt_sounds/bruh.mp3",              500),
("snd_crow",    "Crow",             "snt_sounds/crow.mp3",              250),
("snd_door",    "Open Door",        "snt_sounds/open_door.mp3",         1000),
("snd_gate",    "Open the Gates",   "snt_sounds/open_the_gates.mp3",    250),
("snd_augh",    "Augh",             "snt_sounds/augh.mp3",              1000),
("snd_tada",    "Tada!!",           "snt_sounds/tada.mp3",              250),
("snd_fish",    "FISH",             "snt_sounds/fish.mp3",              500),
("snd_huh",     "Huh",              "snt_sounds/huh.mp3",                500),
("snd_uuua",    "UUUUUUUAA",        "snt_sounds/uuua.mp3",              1000),
("snd_aaau",    "AAAAAAAUU",        "snt_sounds/aaau.mp3",              1000),
("snd_yoyi",    "YOYOI!",           "snt_sounds/yoyoi.mp3",             1000);


INSERT INTO storetrails (ItemId, TrailName, TextureFile, Price)
VALUES
("trl_beam",     "Regular Beam",    "snt_trails/trail_01.vtf",     500),
("trl_weed",     "Weed Leaves",     "snt_trails/trail_02.vtf",     1000),
("trl_star",     "Stars",           "snt_trails/trail_03.vtf",     500),
("trl_dick",     "Dicks",           "snt_trails/trail_04.vtf",     1500),
("trl_psyc",     "Psychedelic",     "snt_trails/trail_05.vtf",     2000);

INSERT INTO storetags (ItemId, TagName, DisplayName, DisplayColor, Price)
VALUES
("tag_frnd",	"Friendly",    	"[Friendly]",      "{community}",          750),
("tag_tryh",    "Tryhard",		"[Tryhard]",       "{goldenrod}",          750),
("tag_dj",      "DJ",			"[DJ]",            "{cornflowerblue}",     750),
("tag_weeb",    "Weeb",			"[Weeb]",          "{lightsalmon}",       5000),
("tag_fury",    "Furry",		"[Furry]",         "{orchid}",            5000),
("tag_femb",    "Femboy",		"[Femboy]",        "{deeppink}",          2500),
("tag_greg",    "Greg",			"[Greg]",          "{peru}",               750),
("tag_poli",    "Politician",	"[Politician]",    "{navy}",              7500),
("tag_frek",    "Freak",		"[Freak]",         "{indigo}",            1000),
("tag_chnk",    "Chonker",		"[Chonker]",       "{lightsteelblue}",     750),
("tag_degn",    "Degenerate",	"[Degenerate]",    "{maroon}",            2500),
("tag_asin",    "Assassin",		"[Assassin]",      "{darkslategray}",     1000),
("tag_god",     "God",			"[God]",           "{yellow}",            5000),
("tag_gdss",    "Goddess",		"[Goddess]",       "{immortal}",          5000),
("tag_lord",    "Lord",			"[Lord]",          "{midnightblue}",      2500),
("tag_lady",    "Lady",			"[Lady]",          "{hotpink}",           2500),
("tag_sexy",    "Sexy",			"[Sexy]",          "{fuschia}",           5000),
("tag_chkn",    "Chicken",		"[Chicken]",       "{sienna}",             750),
("tag_alin",    "Alien",		"[Alien]",         "{lime}",               750),
("tag_stnr",    "Stoner",		"[Stoner]",        "{forestgreen}",       2500),
("tag_alco",    "Alcoholic",	"[Alcoholic]",     "{mediumpurple}",      2500),
("tag_hipp",    "Hippie",		"[Hippie]",        "{lightpink}",         1000),
("tag_drug",    "Druggie",		"[Druggie]",       "{palegoldenrod}",     2500),
("tag_mech",    "Mechanic",		"[Mechanic]",      "{steelblue}",          750),
("tag_goon",    "Gooner",		"[Gooner]",        "{ghostwhite}",       10000),
("tag_snt",     "SurfNTurf",	"[SurfNTurf]",     "{mistyrose}",        10000);

-- ColorTypes: Red Orange Yellow Green Blue Purple Pink Brown Greyscale
-- PackNames: Default, Roblox

-- Default Pack --
INSERT INTO storecolors
VALUES
("aliceblue", 				"Alice Blue", 			"BLUE", 		DEFAULT),
("allies", 					"Allies", 				"GREEN", 		DEFAULT),
("ancient", 				"Ancient", 				"RED", 			DEFAULT),
("antiquewhite", 			"Antique White", 		"BROWN", 		DEFAULT),
("aqua", 					"Aqua", 				"BLUE", 		DEFAULT),
("aquamarine", 				"Aquamarine", 			"GREEN", 		DEFAULT),
("arcana", 					"Arcana", 				"GREEN", 		DEFAULT),
("axis", 					"Axis", 				"RED", 			DEFAULT),
("azure", 					"Azure", 				"BLUE", 		DEFAULT),
("beige", 					"Beige", 				"BROWN", 		DEFAULT),
("bisque", 					"Bisque", 				"BROWN", 		DEFAULT),
("black", 					"Black", 				"GREYSCALE", 	DEFAULT),
("blanchedalmond", 			"Blanched Almond", 		"BROWN", 		DEFAULT),
("blue", 					"Blue", 				"BLUE", 		DEFAULT),
("blueviolet", 				"Blue Violet", 			"PURPLE", 		DEFAULT),
("brown", 					"Brown", 				"BROWN", 		DEFAULT),
("burlywood", 				"Burly Wood", 			"BROWN", 		DEFAULT),
("cadetblue", 				"Cadet Blue", 			"BLUE", 		DEFAULT),
("chartreuse", 				"Charteuse", 			"GREEN", 		DEFAULT),
("chocolate", 				"Chocolate", 			"BROWN", 		DEFAULT),
("collectors", 				"Collectors", 			"RED", 			DEFAULT),
("common", 					"Common", 				"GREYSCALE", 	DEFAULT),
("community", 				"Community", 			"GREEN", 		DEFAULT),
("coral", 					"Coral", 				"ORANGE", 		DEFAULT),
("cornflowerblue", 			"Cornflower Blue", 		"BLUE", 		DEFAULT),
("cornsilk", 				"Corn Silk", 			"BROWN", 		DEFAULT),
("corrupted", 				"Corrupted", 			"RED", 			DEFAULT),
("crimson", 				"Crimson", 				"RED", 			DEFAULT),
("cyan", 					"Cyan", 				"BLUE", 		DEFAULT),
("darkblue", 				"Dark Blue", 			"BLUE", 		DEFAULT),
("darkcyan", 				"Dark Cyan", 			"BLUE", 		DEFAULT),
("darkgoldenrod", 			"Dark Goldenrod",		"YELLOW", 		DEFAULT),
("darkgray", 				"Dark Grey", 			"GREYSCALE",	DEFAULT),
("darkgreen", 				"Dark Green", 			"GREEN", 		DEFAULT),
("darkkhaki", 				"Dark Khaki", 			"BROWN", 		DEFAULT),
("darkmagenta", 			"Dark Magenta", 		"PURPLE", 		DEFAULT),
("darkolivegreen", 			"Dark Olive Green", 	"GREEN", 		DEFAULT),
("darkorange", 				"Dark Orange", 			"Orange", 		DEFAULT),
("darkorchid", 				"Dark Orchid", 			"PURPLE", 		DEFAULT),
("darkred", 				"Dark Red", 			"RED", 			DEFAULT),
("darksalmon", 				"Dark Salmon", 			"Orange", 		DEFAULT),
("darkseagreen",	 		"Dark Sea Green", 		"GREEN", 		DEFAULT),
("darkslateblue", 			"Dark Slate Blue", 		"BLUE", 		DEFAULT),
("darkslategrey", 			"Dark Slate Grey", 		"GREYSCALE", 	DEFAULT),
("darkturquoise", 			"Dark Turquoise", 		"BLUE", 		DEFAULT),
("darkviolet", 				"Dark Violet", 			"PURPLE", 		DEFAULT),
("deeppink", 				"Deep Pink", 			"PINK", 		DEFAULT),
("deepskyblue", 			"Deep Sky Blue", 		"BLUE", 		DEFAULT),
("dimgrey", 				"Dim Grey", 			"GREYSCALE", 	DEFAULT),
("dodgerblue", 				"Dodger Blue", 			"BLUE", 		DEFAULT),
("exalted", 				"Exalted", 				"GREYSCALE", 	DEFAULT),
("firebrick", 				"Fire Brick", 			"RED", 			DEFAULT),
("floralwhite", 			"Floral White", 		"GREYSCALE", 	DEFAULT),
("forestgreen", 			"Forest Green", 		"GREEN", 		DEFAULT),
("frozen", 					"Frozen", 				"BLUE", 		DEFAULT),
("fuchsia", 				"Fuschia", 				"PINK", 		DEFAULT),
("fullblue", 				"Full Blue", 			"BLUE", 		DEFAULT),
("fullred", 				"Full Red", 			"RED", 			DEFAULT),
("gainsboro", 				"Gainsboro", 			"GREYSCALE", 	DEFAULT),
("genuine", 				"Genuine", 				"GREEN", 		DEFAULT),
("ghostwhite", 				"Ghost White", 			"GREYSCALE", 	DEFAULT),
("gold", 					"Gold", 				"YELLOW", 		DEFAULT),
("goldenrod", 				"Goldenrod", 			"YELLOW", 		DEFAULT),
("grey", 					"Grey", 				"GREYSCALE", 	DEFAULT),
("green", 					"Green", 				"GREEN", 		DEFAULT),
("greenyellow", 			"Green Yellow", 		"GREEN", 		DEFAULT),
("haunted", 				"Haunted", 				"GREEN", 		DEFAULT),
("honeydew", 				"Honeydew", 			"GREEN", 		DEFAULT),
("hotpink", 				"Hot Pink", 			"PINK", 		DEFAULT),
("immortal", 				"Immortal", 			"YELLOW", 		DEFAULT),
("indianred", 				"Indian Red", 			"RED", 			DEFAULT),
("indigo", 					"Indigo", 				"PURPLE", 		DEFAULT),
("ivory", 					"Ivory", 				"GREYSCALE", 	DEFAULT),
("khaki", 					"Khaki", 				"BROWN", 		DEFAULT),
("lavender", 				"Lavender", 			"PURPLE", 		DEFAULT),
("lavenderblush", 			"Lavender Blush", 		"PINK", 		DEFAULT),
("lawngreen", 				"Lawn Green", 			"GREEN", 		DEFAULT),
("legendary", 				"Legendary", 			"PURPLE", 		DEFAULT),
("lemonchiffon", 			"Lemon Chiffon", 		"YELLOW", 		DEFAULT),
("lightblue", 				"Light Blue", 			"BLUE",			DEFAULT),
("lightcoral", 				"Light Coral", 			"PINK", 		DEFAULT),
("lightcyan", 				"Light Cyan", 			"BLUE", 		DEFAULT),
("lightgoldenrodyellow", 	"Light Goldenrod", 		"YELLOW", 		DEFAULT),
("lightgrey", 				"Light Grey", 			"GREYSCALE", 	DEFAULT),
("lightgreen", 				"Light Green", 			"GREEN",		DEFAULT),
("lightpink", 				"Light Pink", 			"PINK", 		DEFAULT),
("lightsalmon", 			"Light Salmon", 		"ORANGE", 		DEFAULT),
("lightseagreen", 			"Light Sea Green", 		"GREEN",		DEFAULT),
("lightskyblue", 			"Light Sky Blue", 		"BLUE", 		DEFAULT),
("lightslategrey", 			"Light Slate Grey", 	"GREYSCALE", 	DEFAULT),
("lightsteelblue", 			"Light Steel Blue", 	"BLUE", 		DEFAULT),
("lightyellow", 			"Light Yellow", 		"YELLOW", 		DEFAULT),
("lime", 					"Lime", 				"GREEN", 		DEFAULT),
("limegreen", 				"Lime Green", 			"GREEN", 		DEFAULT),
("linen", 					"Linen", 				"BROWN", 		DEFAULT),
("magenta", 				"Magenta", 				"PINK", 		DEFAULT),
("maroon", 					"Maroon", 				"RED", 			DEFAULT),
("mediumaquamarine", 		"Medium Aquamarine", 	"GREEN", 		DEFAULT),
("mediumblue", 				"Medium Blue", 			"BLUE", 		DEFAULT),
("mediumorchid", 			"Medium Orchid", 		"PURPLE", 		DEFAULT),
("mediumpurple", 			"Medium Purple", 		"PURPLE", 		DEFAULT),
("mediumseagreen", 			"Medium Sea Green", 	"GREEN", 		DEFAULT),
("mediumslateblue", 		"Medium Slate Blue", 	"BLUE", 		DEFAULT),
("mediumspringgreen", 		"Medium Spring Green", 	"GREEN", 		DEFAULT),
("mediumturquoise", 		"Medium Turquoise", 	"BLUE", 		DEFAULT),
("mediumvioletred", 		"Medium Violet Red", 	"PINK", 		DEFAULT),
("midnightblue", 			"Midnight Blue", 		"BLUE", 		DEFAULT),
("mintcream", 				"Mint Cream", 			"GREYSCALE", 	DEFAULT),
("mistyrose", 				"Misty Rose", 			"PINK", 		DEFAULT),
("moccasin", 				"Moccasin", 			"BROWN", 		DEFAULT),
("mythical", 				"Mythical", 			"PURPLE", 		DEFAULT),
("navajowhite", 			"Navajo White", 		"BROWN", 		DEFAULT),
("navy", 					"Navy", 				"BLUE", 		DEFAULT),
("normal", 					"Normal", 				"GREYSCALE", 	DEFAULT),
("oldlace", 				"Old Lace", 			"BROWN", 		DEFAULT),
("olive", 					"Olive", 				"GREEN", 		DEFAULT),
("olivedrab", 				"Olive Drab", 			"GREEN", 		DEFAULT),
("orange", 					"Orange", 				"ORANGE",		DEFAULT),
("orangered", 				"Orange Red", 			"RED", 			DEFAULT),
("orchid", 					"Orchid", 				"PURPLE", 		DEFAULT),
("palegoldenrod", 			"Pale Goldenrod", 		"YELLOW", 		DEFAULT),
("palegreen", 				"Pale Green", 			"GREEN", 		DEFAULT),
("paleturquoise", 			"Pale Turquoise", 		"BLUE", 		DEFAULT),
("palevioletred", 			"Pale Violet Red", 		"RED", 			DEFAULT),
("papayawhip", 				"Papaya Whip", 			"BROWN", 		DEFAULT),
("peachpuff", 				"Peach Puff", 			"BROWN", 		DEFAULT),
("peru", 					"Peru", 				"BROWN", 		DEFAULT),
("pink", 					"Pink", 				"PINK", 		DEFAULT),
("plum", 					"Plum", 				"PURPLE", 		DEFAULT),
("powderblue", 				"Powder Blue", 			"BLUE", 		DEFAULT),
("purple", 					"Purple", 				"PURPLE", 		DEFAULT),
("rare", 					"Rare", 				"BLUE", 		DEFAULT),
("red", 					"Red", 					"RED", 			DEFAULT),
("rosybrown", 				"Rosy Brown", 			"BROWN", 		DEFAULT),
("royalblue", 				"Royal Blue", 			"BLUE", 		DEFAULT),
("saddlebrown", 			"Saddle Brown", 		"BROWN", 		DEFAULT),
("salmon", 					"Salmon", 				"ORANGE", 		DEFAULT),
("sandybrown", 				"Sandy Brown", 			"BROWN", 		DEFAULT),
("seagreen", 				"Sea Green", 			"GREEN", 		DEFAULT),
("seashell", 				"Seashell", 			"GREYSCALE", 	DEFAULT),
("selfmade", 				"Selfmade", 			"GREEN", 		DEFAULT),
("sienna", 					"Sienna", 				"BROWN", 		DEFAULT),
("silver", 					"Silver", 				"GREYSCALE", 	DEFAULT),
("skyblue", 				"Sky Blue", 			"BLUE", 		DEFAULT),
("slateblue", 				"Slate Blue", 			"BLUE", 		DEFAULT),
("slategrey", 				"Slate Grey", 			"GREYSCALE", 	DEFAULT),
("snow", 					"Snow", 				"GREYSCALE", 	DEFAULT),
("springgreen", 			"Spring Green", 		"GREEN", 		DEFAULT),
("steelblue", 				"Steel Blue", 			"BLUE", 		DEFAULT),
("strange", 				"Strange", 				"ORANGE", 		DEFAULT),
("tan", 					"Tan", 					"BROWN", 		DEFAULT),
("teal", 					"Teal", 				"BLUE", 		DEFAULT),
("thistle", 				"Thistle", 				"PURPLE", 		DEFAULT),
("tomato", 					"Tomato", 				"RED", 			DEFAULT),
("turquoise", 				"Turquoise", 			"BLUE", 		DEFAULT),
("uncommon", 				"Uncommon", 			"GREYSCALE", 	DEFAULT),
("unique", 					"Unique", 				"YELLOW", 		DEFAULT),
("unusual", 				"Unusual", 				"PURPLE", 		DEFAULT),
("valve", 					"Valve", 				"PURPLE",	 	DEFAULT),
("vintage", 				"Vintage", 				"BLUE", 		DEFAULT),
("violet", 					"Violet", 				"PURPLE", 		DEFAULT),
("wheat", 					"Wheat", 				"BROWN", 		DEFAULT),
("white", 					"White", 				"GREYSCALE", 	DEFAULT),
("whitesmoke", 				"White Smoke", 			"GREYSCALE", 	DEFAULT),
("yellow", 					"Yellow", 				"YELLOW", 		DEFAULT),
("yellowgreen", 			"Yellow Green", 		"GREEN", 		DEFAULT),

-- Roblox Pack --
("rblxalder", 					    "Alder", 					"PURPLE", 		"ROBLOX"),
("rblxartichoke", 				    "Artichoke", 				"GREEN", 		"ROBLOX"),
("rblxbabyblue", 				    "Baby Blue", 				"BLUE", 		"ROBLOX"),
("rblxbeige", 					    "Beige", 					"BROWN", 		"ROBLOX"),
("rblxblack", 					    "Black", 					"GREYSCALE", 	"ROBLOX"),
("rblxbrickyellow", 			    "Brick Yellow", 			"BROWN", 		"ROBLOX"),
("rblxbrightblue", 				"Bright Blue", 				"BLUE", 		"ROBLOX"),
("rblxbrightbluishgreen", 		    "Bright Blue Green", 		"BLUE", 		"ROBLOX"),
("rblxbrightbluishviolet", 		"Bright Blue Violet", 		"BLUE", 		"ROBLOX"),
("rblxbrightgreen", 			    "Bright Green", 			"GREEN",		"ROBLOX"),
("rblxbrightorange", 			    "Bright Orange", 			"ORANGE", 		"ROBLOX"),
("rblxbrightpurple", 			    "Bright Purple", 			"PINK", 		"ROBLOX"),
("rblxbrightred", 				    "Bright Red", 				"RED", 			"ROBLOX"),
("rblxbrightreddishlilac", 		"Bright Red Lilac", 		"PURPLE", 		"ROBLOX"),
("rblxbrightreddishorange", 	    "Bright Red Orange", 		"ORANGE", 		"ROBLOX"),
("rblxbrightreddishviolet", 	    "Bright Red Violet", 		"PURPLE", 		"ROBLOX"),
("rblxbrightviolet", 			    "Bright Violet", 			"PURPLE", 		"ROBLOX"),
("rblxbrightyellow", 			    "Bright Yellow", 			"YELLOW", 		"ROBLOX"),
("rblxbrightyellowishgreen", 	    "Bright Yellow Green", 		"GREEN", 		"ROBLOX"),
("rblxbrightyellowishorange", 	    "Bright Yellow Orange", 	"ORANGE", 		"ROBLOX"),
("rblxbronze", 					"Bronze", 					"BROWN", 		"ROBLOX"),
("rblxbrown", 					    "Brown", 					"BROWN", 		"ROBLOX"),
("rblxburgundy", 				    "Burgundy", 				"BROWN", 		"ROBLOX"),
("rblxburlap", 					"Burlap", 					"BROWN", 		"ROBLOX"),
("rblxburntsienna", 			    "Burnt Sienna", 			"BROWN", 		"ROBLOX"),
("rblxbuttermilk", 				"Buttermilk", 				"YELLOW", 		"ROBLOX"),
("rblxcadetblue", 				    "Cadet Blue", 				"BLUE", 		"ROBLOX"),
("rblxcamo", 					    "Camo", 					"GREEN", 		"ROBLOX"),
("rblxcarnationpink", 			    "Carnation Pink", 			"PINK", 		"ROBLOX"),
("rblxcashmere", 			   	    "Cashmere", 				"BROWN", 		"ROBLOX"),
("rblxcgabrown", 				    "CGA Brown", 				"BROWN", 		"ROBLOX"),
("rblxcloudygrey", 			   	"Cloudy Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxcocoa", 					    "Cocoa", 					"BROWN", 		"ROBLOX"),
("rblxcoolyellow", 				"Cool Yellow", 				"YELLOW", 		"ROBLOX"),
("rblxcopper", 					"Copper", 					"BROWN", 		"ROBLOX"),
("rblxcork", 					    "Cork", 					"BROWN", 		"ROBLOX"),
("rblxcrimson", 				    "Crimson", 					"RED", 			"ROBLOX"),
("rblxcurry", 					    "Curry", 					"BROWN", 		"ROBLOX"),
("rblxcyan", 					    "Cyan", 					"BLUE", 		"ROBLOX"),
("rblxdaisyorange", 			    "Daisy Orange", 			"YELLOW", 		"ROBLOX"),
("rblxdarkblue", 				    "Dark Blue", 				"BLUE", 		"ROBLOX"),
("rblxdarkcurry", 				    "Dark Curry", 				"BROWN", 		"ROBLOX"),
("rblxdarkgreen", 				    "Dark Green", 				"GREEN", 		"ROBLOX"),
("rblxdarkgrey", 				    "Dark Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxdarkindigo", 				"Dark Indigo", 				"PURPLE", 		"ROBLOX"),
("rblxdarknougat", 				"Dark Nougat", 				"BROWN", 		"ROBLOX"),
("rblxdarkorange", 				"Dark Orange", 				"BROWN", 		"ROBLOX"),
("rblxdarkred", 				    "Dark Red", 				"RED", 			"ROBLOX"),
("rblxdarkroyalblue", 			    "Dark Royal Blue", 			"BLUE", 		"ROBLOX"),
("rblxdarkstonegrey",   			"Dark Stone Grey", 			"GREYSCALE", 	"ROBLOX"),
("rblxdarktaupe", 	    			"Dark Taupe", 				"BROWN", 		"ROBLOX"),
("rblxdeepblue", 		    		"Deep Blue", 				"BLUE", 		"ROBLOX"),
("rblxdeeporange", 				"Deep Orange",				"ORANGE", 		"ROBLOX"),
("rblxdirtbrown", 			    	"Dirt Brown", 				"BROWN", 		"ROBLOX"),
("rblxdoveblue", 				    "Dove Blue", 				"BLUE", 		"ROBLOX"),
("rblxdustyrose",   				"Dusty Rose", 				"RED", 			"ROBLOX"),
("rblxearthblue", 	    			"Earth Blue", 				"BLUE", 		"ROBLOX"),
("rblxearthgreen", 				"Earth Green", 				"GREEN", 		"ROBLOX"),
("rblxearthorange", 	    		"Earth Orange", 			"BROWN", 		"ROBLOX"),
("rblxearthyellow", 		    	"Earth Yellow", 			"BROWN", 		"ROBLOX"),
("rblxeggplant", 				    "Eggplant", 				"PURPLE", 		"ROBLOX"),
("rblxelectricblue",    			"Electric Blue", 			"BLUE", 		"ROBLOX"),
("rblxfadedgreen", 				"Faded Green", 				"GREEN", 		"ROBLOX"),
("rblxfawnbrown", 		    		"Fawn Brown", 				"BROWN", 		"ROBLOX"),
("rblxfireyellow", 				"Fire Yellow", 				"YELLOW", 		"ROBLOX"),
("rblxflamereddishorange", 		"Flame Red Orange", 		"ORANGE", 		"ROBLOX"),
("rblxflameyellowishorange",    	"Flame Yellow Orange", 		"ORANGE", 		"ROBLOX"),
("rblxflint", 					    "Flint", 					"GREYSCALE", 	"ROBLOX"),
("rblxfog",     					"Fog", 						"GREYSCALE", 	"ROBLOX"),
("rblxforestgreen",     			"Forest Green", 			"GREEN", 		"ROBLOX"),
("rblxfossil", 					"Fossil", 					"GREYSCALE", 	"ROBLOX"),
("rblxghostgrey", 		    		"Ghost Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxgold", 				    	"Gold", 					"YELLOW", 		"ROBLOX"),
("rblxgrey", 					    "Grey", 					"GREYSCALE", 	"ROBLOX"),
("rblxgrime", 		    			"Grime", 					"GREEN", 		"ROBLOX"),
("rblxgunmetallic", 	    		"Gun Metallic", 			"GREYSCALE",    "ROBLOX"),
("rblxhotpink", 			    	"Hot Pink", 				"PINK", 		"ROBLOX"),
("rblxhurricanegrey", 			    "Hurricane Grey", 			"GREYSCALE", 	"ROBLOX"),
("rblxinstitutionalwhite", 		"Institutional White", 		"GREYSCALE", 	"ROBLOX"),
("rblxkhaki",   					"Khaki", 					"BROWN", 		"ROBLOX"),
("rblxlapis", 	    				"Lapis", 					"BLUE", 		"ROBLOX"),
("rblxlaurelgreen",     			"Laurel Green", 			"GREEN", 		"ROBLOX"),
("rblxlavender", 		    		"Lavender", 				"PURPLE", 		"ROBLOX"),
("rblxlightblue", 			    	"Light Blue", 				"BLUE", 		"ROBLOX"),
("rblxlightbluishgreen", 		    "Light Blue Green", 		"BLUE", 		"ROBLOX"),
("rblxlightbluishviolet",   		"Light Blue Violet", 		"BLUE", 		"ROBLOX"),
("rblxlightbrickyellow", 	    	"Light Brick Yellow", 		"BROWN", 		"ROBLOX"),
("rblxlightgreenmint", 			"Light Mint Green", 		"GREEN", 		"ROBLOX"),
("rblxlightgrey", 				    "Light Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxlightlilac", 				"Light Lilac", 				"PURPLE", 		"ROBLOX"),
("rblxlightorange", 		    	"Light Orange", 			"BROWN", 		"ROBLOX"),
("rblxlightorangebrown",   		"Light Orange Brown", 		"BROWN", 		"ROBLOX"),
("rblxlightpink", 		    		"Light Pink", 				"PINK", 		"ROBLOX"),
("rblxlightpurple",     			"Light Purple", 			"PINK", 		"ROBLOX"),
("rblxlightred", 		    		"Light Red", 				"RED", 			"ROBLOX"),
("rblxlightredviolet", 			"Light Red Violet", 		"PURPLE", 		"ROBLOX"),
("rblxlightroyalblue", 			"Light Royal Blue", 		"BLUE", 		"ROBLOX"),
("rblxlightstonegrey", 			"Light Stone Grey", 		"GREYSCALE", 	"ROBLOX"),
("rblxlightyellow", 		    	"Light Yellow", 			"YELLOW", 		"ROBLOX"),
("rblxlightyellowishgreen", 	    "Light Yellow Green", 		"GREEN", 		"ROBLOX"),
("rblxlightyellowishorange",    	"Light Yellow Orange", 		"BROWN", 		"ROBLOX"),
("rblxlilac",   					"Lilac", 					"PURPLE", 		"ROBLOX"),
("rblxlilywhite",   				"Lily White", 				"GREYSCALE", 	"ROBLOX"),
("rblxlimegreen", 	    			"Lime Green", 				"GREEN", 		"ROBLOX"),
("rblxlinen", 			    		"Linen", 					"BROWN", 		"ROBLOX"),
("rblxmagenta", 			    	"Magenta", 					"PINK", 		"ROBLOX"),
("rblxmaroon", 					"Maroon", 					"RED", 			"ROBLOX"),
("rblxmauve", 					    "Mauve", 					"PURPLE", 		"ROBLOX"),
("rblxmedbluishgreen", 			"Med Blue Green", 			"BLUE", 		"ROBLOX"),
("rblxmedgreen", 				    "Med. Green", 				"GREEN", 		"ROBLOX"),
("rblxmediumblue", 				"Medium Blue", 				"BLUE", 		"ROBLOX"),
("rblxmediumbluishviolet", 		"Med Blue Violet", 			"BLUE", 		"ROBLOX"),
("rblxmediumlilac",     			"Medium Lilac", 			"PURPLE", 		"ROBLOX"),
("rblxmediumorange", 	    		"Medium Orange", 			"ORANGE", 		"ROBLOX"),
("rblxmediumred", 			    	"Medium Red", 				"RED", 			"ROBLOX"),
("rblxmediumroyalblue", 		    "Medium Royal Blue", 		"BLUE", 		"ROBLOX"),
("rblxmediumstonegrey",     		"Medium Stone Grey", 		"GREYSCALE", 	"ROBLOX"),
("rblxmedredviolet", 		    	"Medium Red Violet", 		"PURPLE", 		"ROBLOX"),
("rblxmedyellowishgreen", 		    "Med Yellow Green", 		"GREEN", 		"ROBLOX"),
("rblxmedyellowishorange", 		"Med Yellow Orange", 		"ORANGE", 		"ROBLOX"),
("rblxmidgrey",     				"Mid Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxmint", 		    			"Mint", 					"GREEN", 		"ROBLOX"),
("rblxmoss", 			    		"Moss", 					"GREEN", 		"ROBLOX"),
("rblxmulberry", 			    	"Mulberry", 				"PURPLE", 		"ROBLOX"),
("rblxnavyblue", 				    "Navy Blue", 				"BLUE", 		"ROBLOX"),
("rblxneonorange", 				"Neon Orange", 				"ORANGE", 		"ROBLOX"),
("rblxnewyeller",   				"New Yeller", 				"YELLOW", 		"ROBLOX"),
("rblxnougat", 					"Nougat", 					"BROWN", 		"ROBLOX"),
("rblxolive",   					"Olive", 					"GREEN", 		"ROBLOX"),
("rblxolivine",     				"Olivine", 					"GREEN", 		"ROBLOX"),
("rblxoyster", 	   				"Oyster", 					"GREYSCALE", 	"ROBLOX"),
("rblxparsleygreen",   			"Parsley Green", 			"GREEN", 		"ROBLOX"),
("rblxpastelblue", 				"Pastel Blue", 				"BLUE", 		"ROBLOX"),
("rblxpastelbluegreen",     		"Pastel Blue Green", 		"BLUE", 		"ROBLOX"),
("rblxpastelbrown", 		    	"Pastel Brown", 			"BROWN", 		"ROBLOX"),
("rblxpastelgreen", 			    "Pastel Green", 			"GREEN", 		"ROBLOX"),
("rblxpastellightblue",     		"Pastel Light Blue", 		"BLUE", 		"ROBLOX"),
("rblxpastelorange",   			"Pastel Orange", 			"ORANGE", 		"ROBLOX"),
("rblxpastelviolet", 	    		"Pastel Violet", 			"PURPLE", 		"ROBLOX"),
("rblxpastelyellow", 		    	"Pastel Yellow", 			"YELLOW", 		"ROBLOX"),
("rblxpearl", 					    "Pearl", 					"GREYSCALE", 	"ROBLOX"),
("rblxpersimmon",   				"Persimmon", 				"ORANGE", 		"ROBLOX"),
("rblxpinecone", 	    			"Pinecone", 				"BROWN", 		"ROBLOX"),
("rblxpink", 			    		"Pink", 					"PINK", 		"ROBLOX"),
("rblxplum", 				    	"Plum", 					"PURPLE", 		"ROBLOX"),
("rblxposphwhite", 				"Posph. White", 			"GREEN", 		"ROBLOX"),
("rblxquillgrey",   				"Quill Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxreallyblack",     			"Really Black", 			"GREYSCALE", 	"ROBLOX"),
("rblxreallyblue", 				"Really Blue", 				"BLUE", 		"ROBLOX"),
("rblxreallyred", 		    		"Really Red", 				"RED", 			"ROBLOX"),
("rblxreddishbrown", 		    	"Reddish Brown", 			"BROWN", 		"ROBLOX"),
("rblxreddishlilac",    			"Red Lilac", 				"PURPLE", 		"ROBLOX"),
("rblxroyalblue", 		    		"Royal Blue", 				"BLUE", 		"ROBLOX"),
("rblxroyalpurple", 		    	"Royal Purple", 			"PURPLE", 		"ROBLOX"),
("rblxrust", 					    "Rust", 					"BROWN", 		"ROBLOX"),
("rblxsagegreen",   				"Sage Green", 				"GREEN", 		"ROBLOX"),
("rblxsalmon", 					"Salmon", 					"PINK", 		"ROBLOX"),
("rblxsandblue", 	    			"Sand Blue", 				"BLUE", 		"ROBLOX"),
("rblxsandgreen", 		    		"Sand Green", 				"GREEN", 		"ROBLOX"),
("rblxsandred", 			    	"Sand Red", 				"RED", 			"ROBLOX"),
("rblxsandviolet", 				"Sand Violet", 				"PURPLE", 		"ROBLOX"),
("rblxseagreen", 				    "Sea Green", 				"GREEN", 		"ROBLOX"),
("rblxseashell",    				"Sea Shell", 				"PINK", 		"ROBLOX"),
("rblxshamrock", 	    			"Shamrock", 				"GREEN", 		"ROBLOX"),
("rblxsilver", 					"Silver", 					"GREYSCALE", 	"ROBLOX"),
("rblxslimegreen", 				"Slime Green", 				"GREEN", 		"ROBLOX"),
("rblxsmokygrey", 		    		"Smoky Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxsteelblue", 			    	"Steel Blue", 				"BLUE", 		"ROBLOX"),
("rblxstormblue", 				    "Storm Blue", 				"BLUE", 		"ROBLOX"),
("rblxsunrise",     				"Sunrise", 					"PURPLE", 		"ROBLOX"),
("rblxtawny", 		    			"Tawny", 					"BROWN", 		"ROBLOX"),
("rblxteal", 			    		"Teal", 					"GREEN", 		"ROBLOX"),
("rblxterracotta", 				"Terra Cotta", 				"BROWN", 		"ROBLOX"),
("rblxtoothpaste", 				"Toothpaste", 				"BLUE", 		"ROBLOX"),
("rblxtrblue", 					"Tr. Blue", 				"BLUE", 		"ROBLOX"),
("rblxtrbrightbluishviolet",    	"Tr. Br. Blue Violet", 		"BLUE", 		"ROBLOX"),
("rblxtrgreen", 				    "Tr. Green", 				"GREEN", 		"ROBLOX"),
("rblxtrlgblue",    				"Light Tr. Blue", 			"BLUE", 		"ROBLOX"),
("rblxtrlilac", 	    			"Tr. Lilac", 				"PURPLE", 		"ROBLOX"),
("rblxtrmedireddishviolet",     	"Med Tr. Red Violet", 		"PINK", 		"ROBLOX"),
("rblxtrred", 	    				"Tr. Red", 					"RED", 			"ROBLOX"),
("rblxtryellow", 	    			"Tr. Yellow", 				"YELLOW", 		"ROBLOX"),
("rblxturquoise", 		    		"Turquoise", 				"BLUE", 		"ROBLOX"),
("rblxwarmyellowishorange",     	"Warm Yellow Orange", 		"BROWN", 		"ROBLOX"),
("rblxwheat", 					    "Wheat", 					"BROWN", 		"ROBLOX"),
("rblxwhite", 					    "White", 					"GREYSCALE", 	"ROBLOX"),

-- VVVVVV Pack --
("vvvvblack",          "blvck",            "GREYSCALE",    "VVVVVV"),
("vvvvmediumgrey",     "m<d^vm gr>y",      "GREYSCALE",    "VVVVVV"),
("vvvvdarkgrey",       "dvrk gr<y",        "GREYSCALE",    "VVVVVV"),
("vvvvlightgrey",      "l^ght gr<y",       "GREYSCALE",    "VVVVVV"),
("vvvvwhite",          "vvh^t<",           "GREYSCALE",    "VVVVVV"),
("vvvvred",            "r<d",              "RED",          "VVVVVV"),
("vvvvvoidred",        "vo^d r<d",         "RED",          "VVVVVV"),
("vvvvdarkred",        "dvrk r<d",         "RED",          "VVVVVV"),
("vvvvmediumred",      "m<d^vm r>d",       "RED",          "VVVVVV"),
("vvvvlightred",       "l^ght r<d",        "RED",          "VVVVVV"),
("vvvvpastelred",      "pvst<l r<d",       "RED",          "VVVVVV"),
("vvvvorange",         "orvng<",           "ORANGE",       "VVVVVV"),
("vvvvvoidorange",     "vo^d orvng<",      "ORANGE",       "VVVVVV"),
("vvvvdarkorange",     "dvrk orvng<",      "ORANGE",       "VVVVVV"),
("vvvvbrown",          "brovvn",           "ORANGE",       "VVVVVV"),
("vvvvlightbrown",     "l^ght brovvn",     "ORANGE",       "VVVVVV"),
("vvvvpastelorange",   "pvst<l orvng>",    "ORANGE",       "VVVVVV"),
("vvvvyellow",         "y<llovv",          "YELLOW",       "VVVVVV"),
("vvvvvoidyellow",     "vo^d y<llovv",     "YELLOW",       "VVVVVV"),
("vvvvdarkyellow",     "dvrk y<llovv",     "YELLOW",       "VVVVVV"),
("vvvvmediumyellow",   "m<d^vm y>llovv",   "YELLOW",       "VVVVVV"),
("vvvvlightyellow",    "l^ght y<llovv",    "YELLOW",       "VVVVVV"),
("vvvvpastelyellow",   "pvst<l y>llovv",   "YELLOW",       "VVVVVV"),
("vvvvgreen",          "gr<>n",            "GREEN",        "VVVVVV"),
("vvvvvoidgreen",      "vo^d gr<>n",       "GREEN",        "VVVVVV"),
("vvvvdarkgreen",      "dvrk gr<>n",       "GREEN",        "VVVVVV"),
("vvvvmediumgreen",    "m<d^um gr<>n",     "GREEN",        "VVVVVV"),
("vvvvlightgreen",     "l^ght gr<>n",      "GREEN",        "VVVVVV"),
("vvvvpastelgreen",    "pvst<l gr<>n",     "GREEN",        "VVVVVV"),
("vvvvblue",           "blv<",             "BLUE",         "VVVVVV"),
("vvvvvoidblue",       "vo^d blv<",        "BLUE",         "VVVVVV"),
("vvvvdarkblue",       "dvrk blv<",        "BLUE",         "VVVVVV"),
("vvvvmediumblue",     "m<d^vm blu>",      "BLUE",         "VVVVVV"),
("vvvvlightblue",      "l^ght blu<",       "BLUE",         "VVVVVV"),
("vvvvpastelblue",     "pvst<l blu>",      "BLUE",         "VVVVVV"),
("vvvvpurple",         "pvrpl<",           "PURPLE",       "VVVVVV"),
("vvvvvoidpurple",     "vo^d pvrpl<",      "PURPLE",       "VVVVVV"),
("vvvvdarkpurple",     "dvrk pvrpl<",      "PURPLE",       "VVVVVV"),
("vvvvmediumpurple",   "m<d^vm pvrpl>",    "PURPLE",       "VVVVVV"),
("vvvvlightpurple",    "l^ght pvrpl<",     "PURPLE",       "VVVVVV"),
("vvvvpastelpurple",   "pvst<l pvrpl>",    "PURPLE",       "VVVVVV"),
("vvvvpink",           "p^nk",             "PINK",         "VVVVVV"),
("vvvvvoidpink",       "vo^d p^nk",        "PINK",         "VVVVVV"),
("vvvvdarkpink",       "dvrk p^nk",        "PINK",         "VVVVVV"),
("vvvvmediumpink",     "m<d^vm p^nk",      "PINK",         "VVVVVV"),
("vvvvlightpink",      "l^ght p^nk",       "PINK",         "VVVVVV"),
("vvvvpastelpink",     "pvst<l p^nk",      "PINK",         "VVVVVV");

INSERT INTO storeserveritems
VALUES
("srv_mspm",   "Micspamming Privileges",   DEFAULT,        750),
("srv_rank",   "Display Rank",             DEFAULT,        1500),
("srv_cnme",   "Colored Name",             DEFAULT,        2500),
("srv_ccht",   "Colored Chat",             DEFAULT,        5000),
("clr_rblx",   "Roblox Color Pack",        "COLORPACK",    10000),
("clr_smod",   "SourceMod Color Pack",     "COLORPACK",    0),
("clr_vvvv",   "VVVVVV Color Pack",        "COLORPACK",    5000);


-- Insert items with unique owners --

INSERT INTO storetags (ItemId, TagName, DisplayName, DisplayColor, Owner)
VALUES
("tag_awd_og",      "OG",				"[OG]",                 "{collectors}",         "[U:1:129770678]"),
("tag_awd_fat",     "Fattest Surfer",	"[Fattest Surfer]",     "{turquoise}",          "[U:1:105279633]"),
("tag_awd_twrp",    "twerp",			"[twerp]",              "{darkorange}",         "[U:1:387291587]"),
("tag_news",    	"New Surfer", 		"[New Surfer]",    		"{white}",              "REGULAR"),
("tag_bgns",    	"Bgn Surfer",		"[Bgn Surfer]",    		"{lightgray}",          "REGULAR"),
("tag_ints",    	"Int Surfer",		"[Int Surfer]",    		"{gray}",               "REGULAR"),
("tag_exps",    	"Exp Surfer",		"[Exp Surfer]",    		"{dimgray}",            "REGULAR"),
("tag_msts",    	"Mst Surfer",		"[Mst Surfer]",    		"{black}",              "REGULAR"),
("tag_erly",        "Early Supporter",	"[Early Supporter]",    "{gold}",               "SUPPORTER"),
("tag_hist",        "Historic",			"[Historic]",           "{vintage}",            "SUPPORTER"),
("tag_frst",        "First Day",		"[First Day]",          "{silver}",             "SUPPORTER"),
("tag_cont",        "Contributor",		"[Contributor]",        "{darkslateblue}",      "CONTRIBUTOR"),
("tag_desg",        "Designer",			"[Designer]",           "{lavenderblush}",      "CONTRIBUTOR"),
("tag_mapr",        "Mapper",			"[Mapper]",             "{aquamarine}",         "CONTRIBUTOR"),
("tag_hlpr",        "Helper",			"[Helper]",             "{mediumaquamarine}",   "CONTRIBUTOR"),
("tag_vip",         "VIP",				"[VIP]",                "{darkviolet}",         "DONATOR"),
("tag_dnte",        "Donator",			"[Donator]",            "{immortal}",           "DONATOR"),
("tag_rich",        "Rich",				"[Rich]",               "{forestgreen}",        "DONATOR");

INSERT INTO storesounds (ItemId, SoundName, SoundFile, Owner)
VALUES
("snd_myst",    "Mystery",  "storesounds/eb_mystery.mp3",    "[U:1:115545346]");

INSERT INTO storeplayers (SteamId, PlayerName)
VALUES
("[U:1:115545346]", "Arcala the Gyiyg"),
("[U:1:129770678]", "bob"),
("[U:1:105279633]", "Emm"),
("[U:1:387291587]", "twerp");

INSERT INTO storeplayeritems (SteamId, ItemId)
VALUES
("[U:1:129770678]", "tag_awd_og"),
("[U:1:105279633]", "tag_awd_fat"),
("[U:1:387291587]", "tag_awd_twrp"),
("[U:1:387291587]", "srv_cnme"),
("[U:1:115545346]", "snd_myst");