-- INSERT --
INSERT INTO storegroups
VALUES
(1, "REGULAR"),
(2, "SUPPORTER"),
(3, "CONTRIBUTOR"),
(4, "DONATOR");

INSERT INTO storesounds (ItemId, SoundName, SoundFile, Cooldown, Price)
VALUES
("snd_crct",    "Correct",                  "snt_sounds/correct.mp3",           1.0,      500),
("snd_wrng",    "Wrong",                    "snt_sounds/wrong.mp3",             1.0,      500),
("snd_bruh",    "Bruh",                     "snt_sounds/bruh.mp3",              1.0,      500),
("snd_crow",    "Crow",                     "snt_sounds/crow.mp3",              0.5,      250),
("snd_door",    "opun dorr",                "snt_sounds/open_door.mp3",         2.0,     1000),
("snd_gate",    "OPEN THE GATE",            "snt_sounds/open_the_gate.mp3",     0.2,      250),
("snd_augh",    "Augh",                     "snt_sounds/augh.mp3",              0.5,     1000),
("snd_tada",    "Tada",                     "snt_sounds/tada.mp3",              1.0,      250),
("snd_fish",    "FISH",                     "snt_sounds/fish.mp3",              1.0,      500),
("snd_huh",     "Huh",                      "snt_sounds/huh.mp3",               0.5,      500),
("snd_uuua",    "UUUA",                     "snt_sounds/uuua.mp3",              1.0,     1000),
("snd_aaau",    "AAAU",                     "snt_sounds/aaau.mp3",              1.0,     1000),
("snd_yoyi",    "YOYOI",                    "snt_sounds/yoyoi.mp3",             1.0,      500),
("snd_airh",    "Air Horn",                 "snt_sounds/air_horn.mp3",          0.2,     1500),
("snd_bttb",    "Bad To The Bone",          "snt_sounds/bttb.mp3",              2.0,     1500),
("snd_cdid",    "Ganon Die",                "snt_sounds/cdi_die.mp3",           0.2,      500),
("snd_wooo",    "Cr1tikal Woo",             "snt_sounds/cr1tikal_woo.mp3",      1.0,     1500),
("snd_doit",    "DOIT",                     "snt_sounds/chinese_doit.mp3",      0.2,      500),
("snd_fwrb",    "Fart (w Reverb)",          "snt_sounds/fwr.mp3",               2.0,     1000),
("snd_lgyd",    "Lego Yoda Scream",         "snt_sounds/lego_yoda.mp3",         0.8,      500),
("snd_mtpe",    "Metal Pipe",               "snt_sounds/metal_pipe.mp3",        1.0,     2000),
("snd_alrt",    "MGS Alert",                "snt_sounds/mgs_alert.mp3",         1.0,     1000),
("snd_oof",     "Oof",                      "snt_sounds/oof.mp3",               0.2,     2000),
("snd_pngs",    "Pingas",                   "snt_sounds/pingas.mp3",            0.5,      500),
("snd_rizz",    "Rizz",                     "snt_sounds/rizz.mp3",              1.0,      500),
("snd_spen",    "SPEEN",                    "snt_sounds/speen.mp3",             1.0,      750),
("snd_sque",    "Squee",                    "snt_sounds/squee.mp3",             0.2,      750),
("snd_sus",     "Among Us Sting",           "snt_sounds/uhoh_sussy.mp3",        3.0,     2500),
("snd_vsce",    "VSauce Scream",            "snt_sounds/vsauce_scream.mp3",     2.0,     1500),
("snd_bonk",    "Bonk",                     "snt_sounds/bonk.mp3",              0.2,     1000),
("snd_bbym",    "Baby Mario",               "snt_sounds/baby_mario.mp3",        0.5,     2500),
("snd_bwmp",    "Boowomp",                  "snt_sounds/boowomp.mp3",           0.3,     1000),
("snd_guts",    "Gutsman's Ass",            "snt_sounds/gutsman.mp3",           2.0,      500),
("snd_womy",    "Woomy",                    "snt_sounds/woomy.mp3",             0.4,      750),
("snd_hkwp",    "Waterphone",               "snt_sounds/hkwphone.mp3",          4.2,     1500),
("snd_hlml",    "Holay Molay",              "snt_sounds/holay_molay.mp3",       0.8,      750),
("snd_lean",    "I LOVE LEAN",              "snt_sounds/lean.mp3",              0.3,     1000),
("snd_bigb",    "TKFB - Big Man's Back",    "snt_sounds/bigman_back.mp3",       2.0,      750),
("snd_bigq",    "TKFB - QUALUUDES!",        "snt_sounds/bigman_ludes.mp3",      2.8,     1000),
("snd_bigl",    "TKFB - Big Man Signin Off","snt_sounds/bigman_signoff.mp3",    1.5,      750),
("snd_bigk",    "TKFB - Happy To See Ya",   "snt_sounds/bigman_happy.mp3",      1.7,      750),
("snd_skbd",    "Skibidi",                  "snt_sounds/skibidi.mp3",           4.0,     2500),
("snd_smk",     "Smoke Weed",               "snt_sounds/snoop_smoke.mp3",       1.8,     1000),
("snd_shia",    "Shia LaBeouf DO IT!",      "snt_sounds/shia_doit.mp3",         0.3,      500),
("snd_come",    "COME!",                    "snt_sounds/come.mp3",              1.0,      500),
("snd_w95s",    "Windows 95 Startup",       "snt_sounds/win95_start.mp3",       5.2,     1000),
("snd_w98s",    "Windows 98 Startup",       "snt_sounds/win98_start.mp3",       6.5,     1000),
("snd_w98l",    "Windows 98 Shutdown",      "snt_sounds/win98_shut.mp3",        3.2,     1000),
("snd_wXPs",    "Windows XP Startup",       "snt_sounds/winXP_start.mp3",       3.3,     1000),
("snd_wXPl",    "Windows XP Shutdown",      "snt_sounds/winXP_shut.mp3",        2.2,     1000),
("snd_klnm",    "Klonoa - Munya",           "snt_sounds/klonoa_munya.mp3",      0.1,      750),
("snd_klnw",    "Klonoa - WAHOO!",          "snt_sounds/klonoa_wahoo.mp3",      0.1,      750),
("snd_yipe",    "Yipeee",                   "snt_sounds/yipee.mp3",             0.2,     2500);

INSERT INTO storetrails (ItemId, TrailName, TextureVTF, TextureVMT, Price)
VALUES
("trl_beam",     "Regular Beam",    "materials/snt_trails/trail_beam.vtf",        "materials/snt_trails/trail_beam.vmt",         500),
("trl_weed",     "Weed Leaves",     "materials/snt_trails/trail_weed.vtf",        "materials/snt_trails/trail_weed.vmt",        1000),
("trl_star",     "Stars",           "materials/snt_trails/trail_stars.vtf",       "materials/snt_trails/trail_stars.vmt",        500),
("trl_dick",     "Dicks",           "materials/snt_trails/trail_phallus.vtf",     "materials/snt_trails/trail_phallus.vmt",     1500),
("trl_rnbw",     "Rainbow",         "materials/snt_trails/trail_rainbow.vtf",     "materials/snt_trails/trail_rainbow.vmt",     2000),
("trl_hrts",     "Hearts",          "materials/snt_trails/trail_hearts.vtf",      "materials/snt_trails/trail_hearts.vmt",      1000),
("trl_swfk",     "Snowflakes",      "materials/snt_trails/trail_snowflakes.vtf",  "materials/snt_trails/trail_snowflakes.vmt",  1500),
("trl_lolo",     "LOLOLOLO",        "materials/snt_trails/trail_lololo.vtf",      "materials/snt_trails/trail_lololo.vmt",      1000),
("trl_wsmh",     "Will Smith",      "materials/snt_trails/trail_willsmith.vtf",   "materials/snt_trails/trail_willsmith.vmt",    750),
("trl_trll",     "Troll Face",      "materials/snt_trails/trail_trollface.vtf",   "materials/snt_trails/trail_trollface.vmt",    750),
("trl_awsm",     "Awesome Face",    "materials/snt_trails/trail_awesomeface.vtf", "materials/snt_trails/trail_awesomeface.vmt", 1000),
("trl_spdg",     "Snoop Dogg",      "materials/snt_trails/trail_snoopdogg.vtf",   "materials/snt_trails/trail_snoopdogg.vmt",   1000),
("trl_tran",     "Trans Flag",      "materials/snt_trails/trail_transflag.vtf",   "materials/snt_trails/trail_transflag.vmt",    250),
("trl_ace",      "Ace Flag",        "materials/snt_trails/trail_aceflag.vtf",     "materials/snt_trails/trail_aceflag.vmt",      250),
("trl_lgbt",     "LGBT Flag",       "materials/snt_trails/trail_lgbtflag.vtf",    "materials/snt_trails/trail_lgbtflag.vmt",     250),
("trl_aro",      "Aro Flag",        "materials/snt_trails/trail_aroflag.vtf",     "materials/snt_trails/trail_aroflag.vmt",      250),
("trl_mtdw",     "Mountain Dew",    "materials/snt_trails/trail_mtndew.vtf",      "materials/snt_trails/trail_mtndew.vmt",      1000),
("trl_mnst",     "Monster Cans",    "materials/snt_trails/trail_mnstrcan.vtf",    "materials/snt_trails/trail_mnstrcan.vmt",    1000),
("trl_nyan",     "Nyan Cat",        "materials/snt_trails/trail_nyancat.vtf",     "materials/snt_trails/trail_nyancat.vmt",     2000);

INSERT INTO storetags (ItemId, TagName, DisplayName, DisplayColor, Price)
VALUES
("tag_frnd",	"Friendly",    	"[Friendly]",       "{community}",          750),
("tag_tryh",    "Tryhard",		"[Tryhard]",        "{goldenrod}",          750),
("tag_dj",      "DJ",			"[DJ]",             "{cornflowerblue}",     750),
("tag_weeb",    "Weeb",			"[Weeb]",           "{lightsalmon}",       5000),
("tag_fury",    "Furry",		"[Furry]",          "{orchid}",            5000),
("tag_femb",    "Femboy",		"[Femboy]",         "{deeppink}",          2500),
("tag_greg",    "Greg",			"[Greg]",           "{peru}",               750),
("tag_poli",    "Politician",	"[Politician]",     "{navy}",              7500),
("tag_frek",    "Freak",		"[Freak]",          "{indigo}",            1000),
("tag_chnk",    "Chonker",		"[Chonker]",        "{lightsteelblue}",     750),
("tag_degn",    "Degenerate",	"[Degenerate]",     "{maroon}",            2500),
("tag_asin",    "Assassin",		"[Assassin]",       "{darkslategray}",     1000),
("tag_god",     "God",			"[God]",            "{yellow}",            5000),
("tag_gdss",    "Goddess",		"[Goddess]",        "{immortal}",          5000),
("tag_lord",    "Lord",			"[Lord]",           "{midnightblue}",      2500),
("tag_lady",    "Lady",			"[Lady]",           "{hotpink}",           2500),
("tag_sexy",    "Sexy",			"[Sexy]",           "{fuschia}",           5000),
("tag_chkn",    "Chicken",		"[Chicken]",        "{sienna}",             750),
("tag_alin",    "Alien",		"[Alien]",          "{lime}",               750),
("tag_stnr",    "Stoner",		"[Stoner]",         "{forestgreen}",       2500),
("tag_alco",    "Alcoholic",	"[Alcoholic]",      "{mediumpurple}",      2500),
("tag_hipp",    "Hippie",		"[Hippie]",         "{lightpink}",         1000),
("tag_drug",    "Druggie",		"[Druggie]",        "{palegoldenrod}",     2500),
("tag_mech",    "Mechanic",		"[Mechanic]",       "{steelblue}",          750),
("tag_goon",    "Gooner",		"[Gooner]",         "{ghostwhite}",       10000),
("tag_homo",    "Homo",         "[Homo]",           "{magenta}",            750),
("tag_hmie",    "Homie",        "[Homie]",          "{steelblue}",         1000),
("tag_stpd",    "Stupid",       "[Stupid]",         "{firebrick}",          500),
("tag_baka",    "Baka",         "[Baka]",           "{cyan}",               750),
("tag_uwu",     "UwU",          "[UwU]",            "{lightpink}",         1500),
("tag_owo",     "OwO",          "[OwO]",            "{lightpink}",         1500),
("tag_shek",    "Shrek",        "[Shrek]",          "{community}",         1500),
("tag_hart",    "Heart",        "[<3]",             "{hotpink}",           2000),
("tag_worm",    "Worm",         "[Worm]",           "{salmon}",             750),
("tag_chad",    "Chad",         "[Chad]",           "{navy}",              1000),
("tag_vrgn",    "Virgin",       "[Virgin]",         "{dimgrey}",           1000),
("tag_bmer",    "Boomer",       "[Boomer]",         "{common}",             750),
("tag_hntr",    "Hunter",       "[Hunter]",         "{olive}",              750),
("tag_wrdo",    "Weirdo",       "[Weirdo]",         "{mediumpurple}",      1000),
("tag_stnk",    "Stinky",       "[Stinky]",         "{darkolivegreen}",    1500),
("tag_exlr",    "Explorer",     "[Explorer]",       "{darkolivegreen}",     250),
("tag_tsun",    "Tsundere",     "[Tsundere]",       "{lightblue}",         1000),
("tag_robt",    "Robot",        "[Robot]",          "{steelblue}",          750),
("tag_kilr",    "Killer",       "[Killer]",         "{darkslategrey}",      500),
("tag_game",    "Gamer",        "[Gamer]",          "{mediumblue}",        2500),
("tag_dvil",    "Devil",        "[Devil]",          "{maroon}",            1000),
("tag_angl",    "Angel",        "[Angel]",          "{snow}",              1000),
("tag_dmon",    "Demon",        "[Demon]",          "{corrupted}",         1000),
("tag_simp",    "Simp",         "[Simp]",           "{plum}",              3000),
("tag_susy",    "Sussy",        "[Sussy]",          "{fullred}",           5000),
("tag_sus",     "Sus",          "[Sus]",            "{fullred}",           5000),
("tag_gnme",    "Gnome",        "[Gnome]",          "{darkseagreen}",      1000),
("tag_gbln",    "Goblin",       "[Goblin]",         "{indianred}",         1000),
("tag_snt",     "SurfNTurf",	"[SurfNTurf]",      "{mistyrose}",         2000),
("tag_trsf",    "Trans F",      "[TransF]",         "{lightpink}",          750),
("tag_trsm",    "Trans M",      "[TransM]",         "{powderblue}",         750),
("tag_trns",    "Transexual",   "[Trans]",          "{seashell}",           750),
("tag_nonb",    "Nonbinary",    "[Nonbinary]",      "{yellow}",             750),
("tag_ace",     "Asexual",      "[Ace]",            "{darkmagenta}",        750),
("tag_aro",     "Aromantic",    "[Aro]",            "{selfmade}",           750),
("tag_gay",     "Gay",          "[Gay]",            "{slateblue}",          750),
("tag_bi",      "Bisexual",     "[Bi]",             "{darkorchid}",         750),
("tag_pan",     "Pansexual",    "[Pan]",            "{deeppink}",           750),
("tag_les",     "Lesbian",      "[Lesbian]",        "{darkorange}",         750);

-- ColorTypes: Red Orange Yellow Green Blue Purple Pink Brown Greyscale
-- PackNames: Default, Roblox

-- Default Pack --
INSERT INTO storecolors
VALUES
("aliceblue", 				"Alice Blue", 			"BLUE", 		DEFAULT),
("allies", 					"Allies", 				"GREEN", 		DEFAULT),
("ancient", 				"Ancient", 				"RED", 			DEFAULT),
("antiquewhite", 			"Antique White", 		"BROWN", 		DEFAULT),
("aqua", 					"Aqua", 				"BLUE", 		DEFAULT),
("aquamarine", 				"Aquamarine", 			"GREEN", 		DEFAULT),
("arcana", 					"Arcana", 				"GREEN", 		DEFAULT),
("axis", 					"Axis", 				"RED", 			DEFAULT),
("azure", 					"Azure", 				"BLUE", 		DEFAULT),
("beige", 					"Beige", 				"BROWN", 		DEFAULT),
("bisque", 					"Bisque", 				"BROWN", 		DEFAULT),
("black", 					"Black", 				"GREYSCALE", 	DEFAULT),
("blanchedalmond", 			"Blanched Almond", 		"BROWN", 		DEFAULT),
("blue", 					"Blue", 				"BLUE", 		DEFAULT),
("blueviolet", 				"Blue Violet", 			"PURPLE", 		DEFAULT),
("brown", 					"Brown", 				"BROWN", 		DEFAULT),
("burlywood", 				"Burly Wood", 			"BROWN", 		DEFAULT),
("cadetblue", 				"Cadet Blue", 			"BLUE", 		DEFAULT),
("chartreuse", 				"Charteuse", 			"GREEN", 		DEFAULT),
("chocolate", 				"Chocolate", 			"BROWN", 		DEFAULT),
("collectors", 				"Collectors", 			"RED", 			DEFAULT),
("common", 					"Common", 				"GREYSCALE", 	DEFAULT),
("community", 				"Community", 			"GREEN", 		DEFAULT),
("coral", 					"Coral", 				"ORANGE", 		DEFAULT),
("cornflowerblue", 			"Cornflower Blue", 		"BLUE", 		DEFAULT),
("cornsilk", 				"Corn Silk", 			"BROWN", 		DEFAULT),
("corrupted", 				"Corrupted", 			"RED", 			DEFAULT),
("crimson", 				"Crimson", 				"RED", 			DEFAULT),
("cyan", 					"Cyan", 				"BLUE", 		DEFAULT),
("darkblue", 				"Dark Blue", 			"BLUE", 		DEFAULT),
("darkcyan", 				"Dark Cyan", 			"BLUE", 		DEFAULT),
("darkgoldenrod", 			"Dark Goldenrod",		"YELLOW", 		DEFAULT),
("darkgray", 				"Dark Grey", 			"GREYSCALE",	DEFAULT),
("darkgreen", 				"Dark Green", 			"GREEN", 		DEFAULT),
("darkkhaki", 				"Dark Khaki", 			"BROWN", 		DEFAULT),
("darkmagenta", 			"Dark Magenta", 		"PURPLE", 		DEFAULT),
("darkolivegreen", 			"Dark Olive Green", 	"GREEN", 		DEFAULT),
("darkorange", 				"Dark Orange", 			"Orange", 		DEFAULT),
("darkorchid", 				"Dark Orchid", 			"PURPLE", 		DEFAULT),
("darkred", 				"Dark Red", 			"RED", 			DEFAULT),
("darksalmon", 				"Dark Salmon", 			"Orange", 		DEFAULT),
("darkseagreen",	 		"Dark Sea Green", 		"GREEN", 		DEFAULT),
("darkslateblue", 			"Dark Slate Blue", 		"BLUE", 		DEFAULT),
("darkslategrey", 			"Dark Slate Grey", 		"GREYSCALE", 	DEFAULT),
("darkturquoise", 			"Dark Turquoise", 		"BLUE", 		DEFAULT),
("darkviolet", 				"Dark Violet", 			"PURPLE", 		DEFAULT),
("deeppink", 				"Deep Pink", 			"PINK", 		DEFAULT),
("deepskyblue", 			"Deep Sky Blue", 		"BLUE", 		DEFAULT),
("dimgrey", 				"Dim Grey", 			"GREYSCALE", 	DEFAULT),
("dodgerblue", 				"Dodger Blue", 			"BLUE", 		DEFAULT),
("exalted", 				"Exalted", 				"GREYSCALE", 	DEFAULT),
("firebrick", 				"Fire Brick", 			"RED", 			DEFAULT),
("floralwhite", 			"Floral White", 		"GREYSCALE", 	DEFAULT),
("forestgreen", 			"Forest Green", 		"GREEN", 		DEFAULT),
("frozen", 					"Frozen", 				"BLUE", 		DEFAULT),
("fuchsia", 				"Fuschia", 				"PINK", 		DEFAULT),
("fullblue", 				"Full Blue", 			"BLUE", 		DEFAULT),
("fullred", 				"Full Red", 			"RED", 			DEFAULT),
("gainsboro", 				"Gainsboro", 			"GREYSCALE", 	DEFAULT),
("genuine", 				"Genuine", 				"GREEN", 		DEFAULT),
("ghostwhite", 				"Ghost White", 			"GREYSCALE", 	DEFAULT),
("gold", 					"Gold", 				"YELLOW", 		DEFAULT),
("goldenrod", 				"Goldenrod", 			"YELLOW", 		DEFAULT),
("grey", 					"Grey", 				"GREYSCALE", 	DEFAULT),
("green", 					"Green", 				"GREEN", 		DEFAULT),
("greenyellow", 			"Green Yellow", 		"GREEN", 		DEFAULT),
("haunted", 				"Haunted", 				"GREEN", 		DEFAULT),
("honeydew", 				"Honeydew", 			"GREEN", 		DEFAULT),
("hotpink", 				"Hot Pink", 			"PINK", 		DEFAULT),
("immortal", 				"Immortal", 			"YELLOW", 		DEFAULT),
("indianred", 				"Indian Red", 			"RED", 			DEFAULT),
("indigo", 					"Indigo", 				"PURPLE", 		DEFAULT),
("ivory", 					"Ivory", 				"GREYSCALE", 	DEFAULT),
("khaki", 					"Khaki", 				"BROWN", 		DEFAULT),
("lavender", 				"Lavender", 			"PURPLE", 		DEFAULT),
("lavenderblush", 			"Lavender Blush", 		"PINK", 		DEFAULT),
("lawngreen", 				"Lawn Green", 			"GREEN", 		DEFAULT),
("legendary", 				"Legendary", 			"PURPLE", 		DEFAULT),
("lemonchiffon", 			"Lemon Chiffon", 		"YELLOW", 		DEFAULT),
("lightblue", 				"Light Blue", 			"BLUE",			DEFAULT),
("lightcoral", 				"Light Coral", 			"PINK", 		DEFAULT),
("lightcyan", 				"Light Cyan", 			"BLUE", 		DEFAULT),
("lightgoldenrodyellow", 	"Light Goldenrod", 		"YELLOW", 		DEFAULT),
("lightgrey", 				"Light Grey", 			"GREYSCALE", 	DEFAULT),
("lightgreen", 				"Light Green", 			"GREEN",		DEFAULT),
("lightpink", 				"Light Pink", 			"PINK", 		DEFAULT),
("lightsalmon", 			"Light Salmon", 		"ORANGE", 		DEFAULT),
("lightseagreen", 			"Light Sea Green", 		"GREEN",		DEFAULT),
("lightskyblue", 			"Light Sky Blue", 		"BLUE", 		DEFAULT),
("lightslategrey", 			"Light Slate Grey", 	"GREYSCALE", 	DEFAULT),
("lightsteelblue", 			"Light Steel Blue", 	"BLUE", 		DEFAULT),
("lightyellow", 			"Light Yellow", 		"YELLOW", 		DEFAULT),
("lime", 					"Lime", 				"GREEN", 		DEFAULT),
("limegreen", 				"Lime Green", 			"GREEN", 		DEFAULT),
("linen", 					"Linen", 				"BROWN", 		DEFAULT),
("magenta", 				"Magenta", 				"PINK", 		DEFAULT),
("maroon", 					"Maroon", 				"RED", 			DEFAULT),
("mediumaquamarine", 		"Medium Aquamarine", 	"GREEN", 		DEFAULT),
("mediumblue", 				"Medium Blue", 			"BLUE", 		DEFAULT),
("mediumorchid", 			"Medium Orchid", 		"PURPLE", 		DEFAULT),
("mediumpurple", 			"Medium Purple", 		"PURPLE", 		DEFAULT),
("mediumseagreen", 			"Medium Sea Green", 	"GREEN", 		DEFAULT),
("mediumslateblue", 		"Medium Slate Blue", 	"BLUE", 		DEFAULT),
("mediumspringgreen", 		"Medium Spring Green", 	"GREEN", 		DEFAULT),
("mediumturquoise", 		"Medium Turquoise", 	"BLUE", 		DEFAULT),
("mediumvioletred", 		"Medium Violet Red", 	"PINK", 		DEFAULT),
("midnightblue", 			"Midnight Blue", 		"BLUE", 		DEFAULT),
("mintcream", 				"Mint Cream", 			"GREYSCALE", 	DEFAULT),
("mistyrose", 				"Misty Rose", 			"PINK", 		DEFAULT),
("moccasin", 				"Moccasin", 			"BROWN", 		DEFAULT),
("mythical", 				"Mythical", 			"PURPLE", 		DEFAULT),
("navajowhite", 			"Navajo White", 		"BROWN", 		DEFAULT),
("navy", 					"Navy", 				"BLUE", 		DEFAULT),
("normal", 					"Normal", 				"GREYSCALE", 	DEFAULT),
("oldlace", 				"Old Lace", 			"BROWN", 		DEFAULT),
("olive", 					"Olive", 				"GREEN", 		DEFAULT),
("olivedrab", 				"Olive Drab", 			"GREEN", 		DEFAULT),
("orange", 					"Orange", 				"ORANGE",		DEFAULT),
("orangered", 				"Orange Red", 			"RED", 			DEFAULT),
("orchid", 					"Orchid", 				"PURPLE", 		DEFAULT),
("palegoldenrod", 			"Pale Goldenrod", 		"YELLOW", 		DEFAULT),
("palegreen", 				"Pale Green", 			"GREEN", 		DEFAULT),
("paleturquoise", 			"Pale Turquoise", 		"BLUE", 		DEFAULT),
("palevioletred", 			"Pale Violet Red", 		"RED", 			DEFAULT),
("papayawhip", 				"Papaya Whip", 			"BROWN", 		DEFAULT),
("peachpuff", 				"Peach Puff", 			"BROWN", 		DEFAULT),
("peru", 					"Peru", 				"BROWN", 		DEFAULT),
("pink", 					"Pink", 				"PINK", 		DEFAULT),
("plum", 					"Plum", 				"PURPLE", 		DEFAULT),
("powderblue", 				"Powder Blue", 			"BLUE", 		DEFAULT),
("purple", 					"Purple", 				"PURPLE", 		DEFAULT),
("rare", 					"Rare", 				"BLUE", 		DEFAULT),
("red", 					"Red", 					"RED", 			DEFAULT),
("rosybrown", 				"Rosy Brown", 			"BROWN", 		DEFAULT),
("royalblue", 				"Royal Blue", 			"BLUE", 		DEFAULT),
("saddlebrown", 			"Saddle Brown", 		"BROWN", 		DEFAULT),
("salmon", 					"Salmon", 				"ORANGE", 		DEFAULT),
("sandybrown", 				"Sandy Brown", 			"BROWN", 		DEFAULT),
("seagreen", 				"Sea Green", 			"GREEN", 		DEFAULT),
("seashell", 				"Seashell", 			"GREYSCALE", 	DEFAULT),
("selfmade", 				"Selfmade", 			"GREEN", 		DEFAULT),
("sienna", 					"Sienna", 				"BROWN", 		DEFAULT),
("silver", 					"Silver", 				"GREYSCALE", 	DEFAULT),
("skyblue", 				"Sky Blue", 			"BLUE", 		DEFAULT),
("slateblue", 				"Slate Blue", 			"BLUE", 		DEFAULT),
("slategrey", 				"Slate Grey", 			"GREYSCALE", 	DEFAULT),
("snow", 					"Snow", 				"GREYSCALE", 	DEFAULT),
("springgreen", 			"Spring Green", 		"GREEN", 		DEFAULT),
("steelblue", 				"Steel Blue", 			"BLUE", 		DEFAULT),
("strange", 				"Strange", 				"ORANGE", 		DEFAULT),
("tan", 					"Tan", 					"BROWN", 		DEFAULT),
("teal", 					"Teal", 				"BLUE", 		DEFAULT),
("thistle", 				"Thistle", 				"PURPLE", 		DEFAULT),
("tomato", 					"Tomato", 				"RED", 			DEFAULT),
("turquoise", 				"Turquoise", 			"BLUE", 		DEFAULT),
("uncommon", 				"Uncommon", 			"GREYSCALE", 	DEFAULT),
("unique", 					"Unique", 				"YELLOW", 		DEFAULT),
("unusual", 				"Unusual", 				"PURPLE", 		DEFAULT),
("valve", 					"Valve", 				"PURPLE",	 	DEFAULT),
("vintage", 				"Vintage", 				"BLUE", 		DEFAULT),
("violet", 					"Violet", 				"PURPLE", 		DEFAULT),
("wheat", 					"Wheat", 				"BROWN", 		DEFAULT),
("white", 					"White", 				"GREYSCALE", 	DEFAULT),
("whitesmoke", 				"White Smoke", 			"GREYSCALE", 	DEFAULT),
("yellow", 					"Yellow", 				"YELLOW", 		DEFAULT),
("yellowgreen", 			"Yellow Green", 		"GREEN", 		DEFAULT),

-- Roblox Pack --
("rblxalder", 					    "Alder", 					"PURPLE", 		"ROBLOX"),
("rblxartichoke", 				    "Artichoke", 				"GREEN", 		"ROBLOX"),
("rblxbabyblue", 				    "Baby Blue", 				"BLUE", 		"ROBLOX"),
("rblxbeige", 					    "Beige", 					"BROWN", 		"ROBLOX"),
("rblxblack", 					    "Black", 					"GREYSCALE", 	"ROBLOX"),
("rblxbrickyellow", 			    "Brick Yellow", 			"BROWN", 		"ROBLOX"),
("rblxbrightblue", 				    "Bright Blue", 				"BLUE", 		"ROBLOX"),
("rblxbrightbluishgreen", 		    "Bright Blue Green", 		"BLUE", 		"ROBLOX"),
("rblxbrightbluishviolet", 		    "Bright Blue Violet", 		"BLUE", 		"ROBLOX"),
("rblxbrightgreen", 			    "Bright Green", 			"GREEN",		"ROBLOX"),
("rblxbrightorange", 			    "Bright Orange", 			"ORANGE", 		"ROBLOX"),
("rblxbrightpurple", 			    "Bright Purple", 			"PINK", 		"ROBLOX"),
("rblxbrightred", 				    "Bright Red", 				"RED", 			"ROBLOX"),
("rblxbrightreddishlilac", 		    "Bright Red Lilac", 		"PURPLE", 		"ROBLOX"),
("rblxbrightreddishorange", 	    "Bright Red Orange", 		"ORANGE", 		"ROBLOX"),
("rblxbrightreddishviolet", 	    "Bright Red Violet", 		"PURPLE", 		"ROBLOX"),
("rblxbrightviolet", 			    "Bright Violet", 			"PURPLE", 		"ROBLOX"),
("rblxbrightyellow", 			    "Bright Yellow", 			"YELLOW", 		"ROBLOX"),
("rblxbrightyellowishgreen", 	    "Bright Yellow Green", 		"GREEN", 		"ROBLOX"),
("rblxbrightyellowishorange", 	    "Bright Yellow Orange", 	"ORANGE", 		"ROBLOX"),
("rblxbronze", 					    "Bronze", 					"BROWN", 		"ROBLOX"),
("rblxbrown", 					    "Brown", 					"BROWN", 		"ROBLOX"),
("rblxburgundy", 				    "Burgundy", 				"BROWN", 		"ROBLOX"),
("rblxburlap", 					    "Burlap", 					"BROWN", 		"ROBLOX"),
("rblxburntsienna", 			    "Burnt Sienna", 			"BROWN", 		"ROBLOX"),
("rblxbuttermilk", 				    "Buttermilk", 				"YELLOW", 		"ROBLOX"),
("rblxcadetblue", 				    "Cadet Blue", 				"BLUE", 		"ROBLOX"),
("rblxcamo", 					    "Camo", 					"GREEN", 		"ROBLOX"),
("rblxcarnationpink", 			    "Carnation Pink", 			"PINK", 		"ROBLOX"),
("rblxcashmere", 			   	    "Cashmere", 				"BROWN", 		"ROBLOX"),
("rblxcgabrown", 				    "CGA Brown", 				"BROWN", 		"ROBLOX"),
("rblxcloudygrey", 			   	    "Cloudy Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxcocoa", 					    "Cocoa", 					"BROWN", 		"ROBLOX"),
("rblxcoolyellow", 				    "Cool Yellow", 				"YELLOW", 		"ROBLOX"),
("rblxcopper", 					    "Copper", 					"BROWN", 		"ROBLOX"),
("rblxcork", 					    "Cork", 					"BROWN", 		"ROBLOX"),
("rblxcrimson", 				    "Crimson", 					"RED", 			"ROBLOX"),
("rblxcurry", 					    "Curry", 					"BROWN", 		"ROBLOX"),
("rblxcyan", 					    "Cyan", 					"BLUE", 		"ROBLOX"),
("rblxdaisyorange", 			    "Daisy Orange", 			"YELLOW", 		"ROBLOX"),
("rblxdarkblue", 				    "Dark Blue", 				"BLUE", 		"ROBLOX"),
("rblxdarkcurry", 				    "Dark Curry", 				"BROWN", 		"ROBLOX"),
("rblxdarkgreen", 				    "Dark Green", 				"GREEN", 		"ROBLOX"),
("rblxdarkgrey", 				    "Dark Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxdarkindigo", 				    "Dark Indigo", 				"PURPLE", 		"ROBLOX"),
("rblxdarknougat", 				    "Dark Nougat", 				"BROWN", 		"ROBLOX"),
("rblxdarkorange", 				    "Dark Orange", 				"BROWN", 		"ROBLOX"),
("rblxdarkred", 				    "Dark Red", 				"RED", 			"ROBLOX"),
("rblxdarkroyalblue", 			    "Dark Royal Blue", 			"BLUE", 		"ROBLOX"),
("rblxdarkstonegrey",   			"Dark Stone Grey", 			"GREYSCALE", 	"ROBLOX"),
("rblxdarktaupe", 	    			"Dark Taupe", 				"BROWN", 		"ROBLOX"),
("rblxdeepblue", 		    		"Deep Blue", 				"BLUE", 		"ROBLOX"),
("rblxdeeporange", 				    "Deep Orange",				"ORANGE", 		"ROBLOX"),
("rblxdirtbrown", 			    	"Dirt Brown", 				"BROWN", 		"ROBLOX"),
("rblxdoveblue", 				    "Dove Blue", 				"BLUE", 		"ROBLOX"),
("rblxdustyrose",   				"Dusty Rose", 				"RED", 			"ROBLOX"),
("rblxearthblue", 	    			"Earth Blue", 				"BLUE", 		"ROBLOX"),
("rblxearthgreen", 				    "Earth Green", 				"GREEN", 		"ROBLOX"),
("rblxearthorange", 	    		"Earth Orange", 			"BROWN", 		"ROBLOX"),
("rblxearthyellow", 		    	"Earth Yellow", 			"BROWN", 		"ROBLOX"),
("rblxeggplant", 				    "Eggplant", 				"PURPLE", 		"ROBLOX"),
("rblxelectricblue",    			"Electric Blue", 			"BLUE", 		"ROBLOX"),
("rblxfadedgreen", 				    "Faded Green", 				"GREEN", 		"ROBLOX"),
("rblxfawnbrown", 		    		"Fawn Brown", 				"BROWN", 		"ROBLOX"),
("rblxfireyellow", 				    "Fire Yellow", 				"YELLOW", 		"ROBLOX"),
("rblxflamereddishorange", 		    "Flame Red Orange", 		"ORANGE", 		"ROBLOX"),
("rblxflameyellowishorange",    	"Flame Yellow Orange", 		"ORANGE", 		"ROBLOX"),
("rblxflint", 					    "Flint", 					"GREYSCALE", 	"ROBLOX"),
("rblxfog",     					"Fog", 						"GREYSCALE", 	"ROBLOX"),
("rblxforestgreen",     			"Forest Green", 			"GREEN", 		"ROBLOX"),
("rblxfossil", 					    "Fossil", 					"GREYSCALE", 	"ROBLOX"),
("rblxghostgrey", 		    		"Ghost Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxgold", 				    	"Gold", 					"YELLOW", 		"ROBLOX"),
("rblxgrey", 					    "Grey", 					"GREYSCALE", 	"ROBLOX"),
("rblxgrime", 		    			"Grime", 					"GREEN", 		"ROBLOX"),
("rblxgunmetallic", 	    		"Gun Metallic", 			"GREYSCALE",    "ROBLOX"),
("rblxhotpink", 			    	"Hot Pink", 				"PINK", 		"ROBLOX"),
("rblxhurricanegrey", 			    "Hurricane Grey", 			"GREYSCALE", 	"ROBLOX"),
("rblxinstitutionalwhite", 		    "Institutional White", 		"GREYSCALE", 	"ROBLOX"),
("rblxkhaki",   					"Khaki", 					"BROWN", 		"ROBLOX"),
("rblxlapis", 	    				"Lapis", 					"BLUE", 		"ROBLOX"),
("rblxlaurelgreen",     			"Laurel Green", 			"GREEN", 		"ROBLOX"),
("rblxlavender", 		    		"Lavender", 				"PURPLE", 		"ROBLOX"),
("rblxlightblue", 			    	"Light Blue", 				"BLUE", 		"ROBLOX"),
("rblxlightbluishgreen", 		    "Light Blue Green", 		"BLUE", 		"ROBLOX"),
("rblxlightbluishviolet",   		"Light Blue Violet", 		"BLUE", 		"ROBLOX"),
("rblxlightbrickyellow", 	    	"Light Brick Yellow", 		"BROWN", 		"ROBLOX"),
("rblxlightgreenmint", 			    "Light Mint Green", 		"GREEN", 		"ROBLOX"),
("rblxlightgrey", 				    "Light Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxlightlilac", 				    "Light Lilac", 				"PURPLE", 		"ROBLOX"),
("rblxlightorange", 		    	"Light Orange", 			"BROWN", 		"ROBLOX"),
("rblxlightorangebrown",   		    "Light Orange Brown", 		"BROWN", 		"ROBLOX"),
("rblxlightpink", 		    		"Light Pink", 				"PINK", 		"ROBLOX"),
("rblxlightpurple",     			"Light Purple", 			"PINK", 		"ROBLOX"),
("rblxlightred", 		    		"Light Red", 				"RED", 			"ROBLOX"),
("rblxlightredviolet", 			    "Light Red Violet", 		"PURPLE", 		"ROBLOX"),
("rblxlightroyalblue", 			    "Light Royal Blue", 		"BLUE", 		"ROBLOX"),
("rblxlightstonegrey", 			    "Light Stone Grey", 		"GREYSCALE", 	"ROBLOX"),
("rblxlightyellow", 		    	"Light Yellow", 			"YELLOW", 		"ROBLOX"),
("rblxlightyellowishgreen", 	    "Light Yellow Green", 		"GREEN", 		"ROBLOX"),
("rblxlightyellowishorange",    	"Light Yellow Orange", 		"BROWN", 		"ROBLOX"),
("rblxlilac",   					"Lilac", 					"PURPLE", 		"ROBLOX"),
("rblxlilywhite",   				"Lily White", 				"GREYSCALE", 	"ROBLOX"),
("rblxlimegreen", 	    			"Lime Green", 				"GREEN", 		"ROBLOX"),
("rblxlinen", 			    		"Linen", 					"BROWN", 		"ROBLOX"),
("rblxmagenta", 			    	"Magenta", 					"PINK", 		"ROBLOX"),
("rblxmaroon", 					    "Maroon", 					"RED", 			"ROBLOX"),
("rblxmauve", 					    "Mauve", 					"PURPLE", 		"ROBLOX"),
("rblxmedbluishgreen", 			    "Medium Blue Green", 		"BLUE", 		"ROBLOX"),
("rblxmedgreen", 				    "Medium Green", 			"GREEN", 		"ROBLOX"),
("rblxmediumblue", 				    "Medium Blue", 				"BLUE", 		"ROBLOX"),
("rblxmediumbluishviolet", 		    "Medium Blue Violet", 		"BLUE", 		"ROBLOX"),
("rblxmediumlilac",     			"Medium Lilac", 			"PURPLE", 		"ROBLOX"),
("rblxmediumorange", 	    		"Medium Orange", 			"ORANGE", 		"ROBLOX"),
("rblxmediumred", 			    	"Medium Red", 				"RED", 			"ROBLOX"),
("rblxmediumroyalblue", 		    "Medium Royal Blue", 		"BLUE", 		"ROBLOX"),
("rblxmediumstonegrey",     		"Medium Stone Grey", 		"GREYSCALE", 	"ROBLOX"),
("rblxmedredviolet", 		    	"Medium Red Violet", 		"PURPLE", 		"ROBLOX"),
("rblxmedyellowishgreen", 		    "Medium Yellow Green", 		"GREEN", 		"ROBLOX"),
("rblxmedyellowishorange", 		    "Medium Yellow Orange", 	"ORANGE", 		"ROBLOX"),
("rblxmidgrey",     				"Mid Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxmint", 		    			"Mint", 					"GREEN", 		"ROBLOX"),
("rblxmoss", 			    		"Moss", 					"GREEN", 		"ROBLOX"),
("rblxmulberry", 			    	"Mulberry", 				"PURPLE", 		"ROBLOX"),
("rblxnavyblue", 				    "Navy Blue", 				"BLUE", 		"ROBLOX"),
("rblxneonorange", 				    "Neon Orange", 				"ORANGE", 		"ROBLOX"),
("rblxnewyeller",   				"New Yeller", 				"YELLOW", 		"ROBLOX"),
("rblxnougat", 					    "Nougat", 					"BROWN", 		"ROBLOX"),
("rblxolive",   					"Olive", 					"GREEN", 		"ROBLOX"),
("rblxolivine",     				"Olivine", 					"GREEN", 		"ROBLOX"),
("rblxoyster", 	   				    "Oyster", 					"GREYSCALE", 	"ROBLOX"),
("rblxparsleygreen",   			    "Parsley Green", 			"GREEN", 		"ROBLOX"),
("rblxpastelblue", 				    "Pastel Blue", 				"BLUE", 		"ROBLOX"),
("rblxpastelbluegreen",     		"Pastel Blue Green", 		"BLUE", 		"ROBLOX"),
("rblxpastelbrown", 		    	"Pastel Brown", 			"BROWN", 		"ROBLOX"),
("rblxpastelgreen", 			    "Pastel Green", 			"GREEN", 		"ROBLOX"),
("rblxpastellightblue",     		"Pastel Light Blue", 		"BLUE", 		"ROBLOX"),
("rblxpastelorange",   			    "Pastel Orange", 			"ORANGE", 		"ROBLOX"),
("rblxpastelviolet", 	    		"Pastel Violet", 			"PURPLE", 		"ROBLOX"),
("rblxpastelyellow", 		    	"Pastel Yellow", 			"YELLOW", 		"ROBLOX"),
("rblxpearl", 					    "Pearl", 					"GREYSCALE", 	"ROBLOX"),
("rblxpersimmon",   				"Persimmon", 				"ORANGE", 		"ROBLOX"),
("rblxpinecone", 	    			"Pinecone", 				"BROWN", 		"ROBLOX"),
("rblxpink", 			    		"Pink", 					"PINK", 		"ROBLOX"),
("rblxplum", 				    	"Plum", 					"PURPLE", 		"ROBLOX"),
("rblxposphwhite", 				    "Posph. White", 			"GREYSCALE", 	"ROBLOX"),
("rblxquillgrey",   				"Quill Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxreallyblack",     			"Really Black", 			"GREYSCALE", 	"ROBLOX"),
("rblxreallyblue", 				    "Really Blue", 				"BLUE", 		"ROBLOX"),
("rblxreallyred", 		    		"Really Red", 				"RED", 			"ROBLOX"),
("rblxreddishbrown", 		    	"Reddish Brown", 			"BROWN", 		"ROBLOX"),
("rblxreddishlilac",    			"Red Lilac", 				"PURPLE", 		"ROBLOX"),
("rblxroyalblue", 		    		"Royal Blue", 				"BLUE", 		"ROBLOX"),
("rblxroyalpurple", 		    	"Royal Purple", 			"PURPLE", 		"ROBLOX"),
("rblxrust", 					    "Rust", 					"BROWN", 		"ROBLOX"),
("rblxsagegreen",   				"Sage Green", 				"GREEN", 		"ROBLOX"),
("rblxsalmon", 					    "Salmon", 					"PINK", 		"ROBLOX"),
("rblxsandblue", 	    			"Sand Blue", 				"BLUE", 		"ROBLOX"),
("rblxsandgreen", 		    		"Sand Green", 				"GREEN", 		"ROBLOX"),
("rblxsandred", 			    	"Sand Red", 				"RED", 			"ROBLOX"),
("rblxsandviolet", 				    "Sand Violet", 				"PURPLE", 		"ROBLOX"),
("rblxseagreen", 				    "Sea Green", 				"GREEN", 		"ROBLOX"),
("rblxseashell",    				"Sea Shell", 				"PINK", 		"ROBLOX"),
("rblxshamrock", 	    			"Shamrock", 				"GREEN", 		"ROBLOX"),
("rblxsilver", 					    "Silver", 					"GREYSCALE", 	"ROBLOX"),
("rblxslimegreen", 				    "Slime Green", 				"GREEN", 		"ROBLOX"),
("rblxsmokygrey", 		    		"Smoky Grey", 				"GREYSCALE", 	"ROBLOX"),
("rblxsteelblue", 			    	"Steel Blue", 				"BLUE", 		"ROBLOX"),
("rblxstormblue", 				    "Storm Blue", 				"BLUE", 		"ROBLOX"),
("rblxsunrise",     				"Sunrise", 					"PURPLE", 		"ROBLOX"),
("rblxtawny", 		    			"Tawny", 					"BROWN", 		"ROBLOX"),
("rblxteal", 			    		"Teal", 					"BLUE", 		"ROBLOX"),
("rblxterracotta", 				    "Terra Cotta", 				"BROWN", 		"ROBLOX"),
("rblxtoothpaste", 				    "Toothpaste", 				"BLUE", 		"ROBLOX"),
("rblxtrblue", 					    "Tr. Blue", 				"BLUE", 		"ROBLOX"),
("rblxtrbrightbluishviolet",    	"Tr. Br. Blue Violet", 		"BLUE", 		"ROBLOX"),
("rblxtrgreen", 				    "Tr. Green", 				"GREEN", 		"ROBLOX"),
("rblxtrlgblue",    				"Light Tr. Blue", 			"BLUE", 		"ROBLOX"),
("rblxtrlilac", 	    			"Tr. Lilac", 				"PURPLE", 		"ROBLOX"),
("rblxtrmedireddishviolet",     	"Med Tr. Red Violet", 		"PINK", 		"ROBLOX"),
("rblxtrred", 	    				"Tr. Red", 					"RED", 			"ROBLOX"),
("rblxtryellow", 	    			"Tr. Yellow", 				"YELLOW", 		"ROBLOX"),
("rblxturquoise", 		    		"Turquoise", 				"BLUE", 		"ROBLOX"),
("rblxwarmyellowishorange",     	"Warm Yellow Orange", 		"BROWN", 		"ROBLOX"),
("rblxwheat", 					    "Wheat", 					"BROWN", 		"ROBLOX"),
("rblxwhite", 					    "White", 					"GREYSCALE", 	"ROBLOX");

INSERT INTO storeserveritems
VALUES
("srv_mspm",        "Micspamming Privileges",   "The ability to use our micspam system\nUse /micspam help for more info!",                      DEFAULT,     250),
("srv_rank",        "Display Rank",             "The ability to have your rank\ndisplayed in chat, before or\nafter your name.",                DEFAULT,    1500),
("srv_cnme",        "Colored Name",             "Color your name using colors\nprovided by our palettes!",                                      DEFAULT,    5000),
("srv_ccht",        "Colored Chat",             "Color your chat using colors\nprovided by our palettes!",                                      DEFAULT,    5000),
("srv_csnd",        "Entry / Exit Sounds",      "The ability to equip a sound that\nplays when you enter or leave\nthe server.",                DEFAULT,    5000),
("srv_dsnd",        "Death Sounds",             "Play a sound when you die!",                                                                   DEFAULT,    5000),
("srv_ssnd",        "Server Sounds",            "Get all of the sounds the server\nuses added to your inventory!",                              DEFAULT,    5000),
("srv_spcs",        "Spectator Sounds",         "Use your soundboard while in spectator!",                                                      DEFAULT,    7500),
("srv_clr_rblx",    "Roblox Palette",           "BrickColors ripped straight from the roblox wiki!\nUse them to spice up your name / chat!",    DEFAULT,    2500);

-- Insert items with unique owners --

INSERT INTO storetags (ItemId, TagName, DisplayName, DisplayColor, Owner)
VALUES
("tag_awd_og",      "OG",				"[OG]",                 "{collectors}",         "[U:1:129770678]"),
("tag_awd_fat",     "Fattest Surfer",	"[Fattest Surfer]",     "{turquoise}",          "[U:1:105279633]"),
("tag_awd_twrp",    "twerp",			"[twerp]",              "{darkorange}",         "[U:1:387291587]"),
("tag_news",    	"New Surfer", 		"[New Surfer]",    		"{white}",              "REGULAR"),
("tag_bgns",    	"Bgn Surfer",		"[Bgn Surfer]",    		"{lightgray}",          "REGULAR"),
("tag_ints",    	"Int Surfer",		"[Int Surfer]",    		"{gray}",               "REGULAR"),
("tag_exps",    	"Exp Surfer",		"[Exp Surfer]",    		"{dimgray}",            "REGULAR"),
("tag_msts",    	"Mst Surfer",		"[Mst Surfer]",    		"{black}",              "REGULAR"),
("tag_pirt",        "Pirate",           "[Pirate]",             "{black}",              "REGULAR"),
("tag_erly",        "Early Supporter",	"[Early Supporter]",    "{gold}",               "SUPPORTER"),
("tag_hist",        "Historic",			"[Historic]",           "{vintage}",            "SUPPORTER"),
("tag_frst",        "First Day",		"[First Day]",          "{silver}",             "SUPPORTER"),
("tag_cont",        "Contributor",		"[Contributor]",        "{darkslateblue}",      "CONTRIBUTOR"),
("tag_desg",        "Designer",			"[Designer]",           "{lavenderblush}",      "CONTRIBUTOR"),
("tag_mapr",        "Mapper",			"[Mapper]",             "{aquamarine}",         "CONTRIBUTOR"),
("tag_hlpr",        "Helper",			"[Helper]",             "{mediumaquamarine}",   "CONTRIBUTOR"),
("tag_vip",         "VIP",				"[VIP]",                "{darkviolet}",         "DONATOR"),
("tag_dnte",        "Donator",			"[Donator]",            "{immortal}",           "DONATOR"),
("tag_rich",        "Rich",				"[Rich]",               "{forestgreen}",        "DONATOR");

INSERT INTO storesounds (ItemId, SoundName, SoundFile, Cooldown, Owner)
VALUES
("snd_myst",            "Mystery",      "snt_sounds/eb_mystery.mp3",        2.2,        "[U:1:115545346]"),
("snd_yarr",            "Yarr",         "snt_sounds/ypp_yarr.mp3",          1.0,                "REGULAR"),
("snd_srv_sting",       "YPP Sting",    "snt_sounds/ypp_sting.mp3",         1.2,                "SYSTEM"),
("snd_srv_login",       "YPP Login",    "snt_sounds/ypp_login.mp3",         2.0,                "SYSTEM"),
("snd_mspam_warn1",     "YPP Whistle",  "snt_sounds/ypp_whistle.mp3",       1.2,                "SYSTEM"),
("snd_mspam_warn2",     "YPP Sting 2",  "snt_sounds/ypp_sting2.mp3",        1.2,                "SYSTEM");

INSERT INTO storetrails
VALUES
("trl_pflg",    "Pirate Flag",  "materials/snt_trails/trail_pirateflag.vtf", "materials/snt_trails/trail_pirateflag.vmt", 0, "REGUALR", 0);

INSERT INTO storeplayers (SteamId, PlayerName)
VALUES
("[U:1:115545346]", "Arcala the Gyiyg"),
("[U:1:129770678]", "bob"),
("[U:1:105279633]", "Emm"),
("[U:1:387291587]", "twerp");

INSERT INTO storeserveritems (ItemId, ItemName, ItemDesc, Owner)
VALUES
("srv_clr_srcm", "SourceMod Color Pack", "The default color pack.\nYou get this even if you can't color your name/text.", "REGULAR");

INSERT INTO storeplayeritems (SteamId, ItemId)
VALUES
("[U:1:129770678]", "tag_awd_og"),
("[U:1:105279633]", "tag_awd_fat"),
("[U:1:387291587]", "tag_awd_twrp"),
("[U:1:387291587]", "srv_cnme"),
("[U:1:387291587]", "snd_bigb"),
("[U:1:387291587]", "snd_bigq"),
("[U:1:387291587]", "snd_bigl"),
("[U:1:387291587]", "snd_bigk"),
("[U:1:115545346]", "snd_myst");
